# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app: mosquitto
spec: #specs des Deployments
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto # ich manage pods/templates die app: mosquitto haben
  template:
    metadata:
      labels:
        app: mosquitto
    spec: # specs/Blueprint für den Container
      # siehe https://hub.docker.com/_/eclipse-mosquitto/
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.12
          ports:
            # wenn nicht anders angegeben ist containerPort==PodPort
            - containerPort: 1883
          volumeMounts:
            # Wie spielen mountPath und subPath zusammen?
            - mountPath: /mosquitto/config
              name: mosquitto-config-volume
      volumes:
        - name: mosquitto-config-volume
          configMap:
            name: mosquitto-config
